server:
  port: 2024
spring:
   application:
     name: user-data-api
   datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://localhost:3306/praveen_2
     username: root
     password: 131612
   jpa:
     database-platform: org.hibernate.dialect.MySQL5Dialect 
     generate-ddl: true
     hibernate: 
         ddl-auto: update
         generate_statastics: true
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    serviceUrl:
     defaultZone: http://localhost:8761/eureka
logging:
  level:
    org:
     springframework:
       web: DEBUG
    root: WARN
    
jwt:
  secret: akhmsecret 
